### ISSUE TITLE
Can't running

### ISSUE THREAD

**Issue by babyrig** [CryptoGnome/Bybit-Futures-Bot#7]
Hi I am trying to run this but I got errors from the beginner:

python3 websocket.py
Traceback (most recent call last):
  File "websocket.py", line 14, in <module>
    settings = json.load(fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 157)

Then I go to that line and change from settings = json.load(fp) to "settings = json.load(fp)" or 'settings = json.load(fp)'
and try to run again:

python3 websocket.py
Traceback (most recent call last):
  File "websocket.py", line 32, in <module>
    client = bybitwrapper.bybit(test=False, api_key=settings['key'], api_secret=settings['secret'])
TypeError: string indices must be integers
Exception ignored in: <function Exchange.__del__ at 0x7f403c4bc310>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 399, in __del__
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 736, in close
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 325, in close
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 211, in clear
  File "/usr/lib/python3/dist-packages/urllib3/_collections.py", line 94, in clear
TypeError: 'NoneType' object is not callable

Any tips here ?

**Comment by beegyn** [comment]
Hello babyrig. 

To fix this please do not change the code. The error is within the settings file.

{
  "exchange": "bybit",
  "key": "key-here",
  "secret": "secret-here",
  "check_leverage": "false",
  "cooldown": 0.25,    **<-- remove the ,** 
}

And please look at the pull request I made because there are important changes that have to be made to the code because otherwise you will not make any profits at all. (DCA only when in profit, no lickvalue used and the calculation of TP makes you lose money) :)

**Comment by CryptoGnome** [comment]
good find, merged changes
